name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  install-pip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.10"
      - name: Install with pip
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install .

  install-uv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v10.0.1
      - name: Install with uv
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install .
